### ISSUE TITLE
Support for phpstan 0.13 & 0.14

### ISSUE THREAD

**Issue by KartaviK** [ergebnis/phpstan-rules#205]
Please, add support for phpstan versions 0.13 and 0.14

**Comment by staabm** [comment]
There is no phpstan 0.13 or 0.14

**Comment by localheinz** [comment]
@KartaviK 

I'll see what I can do as soon as `phpstan/phpstan:~0.13` and `phpstan/phpstan:~0.13` are available!

🤓
