### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by rask** [ergebnis/phpstan-rules#285]
I'm greeted with composer version restriction errors when installing on PHP 8.0 RC1, saying this package requires PHP 7.

Are you waiting for PHP 8.0 to become stable (i.e. leave beta) before providing an upgrade for this package or are you open to making this work with pre-stable versions of 8.0 as well?

**Comment by localheinz** [comment]
@rask 

Will take a look at the weekend!

**Comment by localheinz** [comment]
@rask 

Allowing installation on PHP 8.0 with https://github.com/ergebnis/phpstan-rules/releases/tag/0.15.3.

Will follow up with official support!

Let's keep this issue open until then.

**Comment by localheinz** [comment]
@rask 

Feel free to open a pull request, though!

🤓

**Comment by localheinz** [comment]
@rask 

Closing, feel free to reopen if there are any issues!
