### ISSUE TITLE
`abstract` Doctrine entities should not require `final` methods

### ISSUE THREAD

**Issue by localheinz** [ergebnis/phpstan-rules#295]
`abstract` Doctrine entities should not require `final` methods.

`final` methods will not work here because proxies will want to override them.

/cc @OskarStark

**Comment by OskarStark** [comment]
Shall we keep this open @localheinz ?

**Comment by OskarStark** [comment]
As there is an open PR already let's keep it open please

**Comment by OskarStark** [comment]
Keep it open please
