### ISSUE TITLE
Remove or separate dependabot fixes on tag release pages

### ISSUE THREAD

**Issue by mfn** [ergebnis/phpstan-rules#297]
#### Steps required to reproduce the problem

1. go to https://github.com/ergebnis/phpstan-rules/releases/tag/0.15.3
2. play detective to find _actual_ changes
  ![image](https://user-images.githubusercontent.com/87493/97725178-2ae26f80-1ace-11eb-91e4-87c861167f11.png)

It's night impossible due to 95% dependabot noise.

#### Expected Result

Only show relevant project changes (I identified two comments making sense) or separate them in a more readable way. I figure a release summary should be for humans and not machines.

Thanks 😄

**Comment by localheinz** [comment]
@mfn 

You can find all relevant changes in [`CHANGELOG.md`](https://github.com/ergebnis/phpstan-rules/blob/main/CHANGELOG.md).

**Comment by mfn** [comment]
I'm aware, but when being notified of new releases, the first stop is the github release package, which at the moment is not very suited for human consumption and thus requires extra steps => bad DX. Thanks

**Comment by localheinz** [comment]
@mfn 

Feel free to [sponsor me](https://github.com/sponsors/localheinz), and I will consider making some changes. 

On a separate note, this is the first time I have heard this complaint for building software you get to use for free, which I build in my free time.

**Comment by mfn** [comment]
Thanks :-)
