### ISSUE TITLE
Suggestion: Suppress `NoParameterWithContainerTypeDeclarationRule` in a bundle's `loadExtension()`

### ISSUE THREAD

**Issue by ThomasLandauer** [ergebnis/phpstan-rules#475]
When using Symfony's new way to set up a bundle https://symfony.com/doc/current/bundles/extension.html#loading-services-directly-in-your-bundle-class, the following error is emitted by [NoParameterWithContainerTypeDeclarationRule](https://github.com/ergebnis/phpstan-rules/blob/main/src/Methods/NoParameterWithContainerTypeDeclarationRule.php#L149):

 > Method FooBundle\FooBundle::loadExtension() has a parameter $builder with a type declaration of Symfony\Component\DependencyInjection\ContainerBuilder, but containers should not be injected.

I'm suggesting to make an exception for this case, i.e. don't show an error if the method name is `xxxBundle::loadExtension()`

**Comment by localheinz** [comment]
@ThomasLandauer 

I do not want to add Symfony as a dependency here and deal with it - just ignore and add the error to the [baseline](https://phpstan.org/user-guide/baseline).
