### ISSUE TITLE
NoEmptyRule is redundant

### ISSUE THREAD

**Issue by enumag** [ergebnis/phpstan-rules#524]
This package is recommended to be used on top of [phpstan/phpstan-strict-rules](https://github.com/phpstan/phpstan-strict-rules) which already has a [DisallowedEmptyRule](https://github.com/phpstan/phpstan-strict-rules/blob/1.5.x/src/Rules/DisallowedConstructs/DisallowedEmptyRule.php). As such I think the NoEmptyRule should be removed from this package.

I can send a pull request if you agree.

**Comment by localheinz** [comment]
I would appreciate it, @enumag!
