### ISSUE TITLE
`PrivateInFinalClassRule` should not report trait methods

### ISSUE THREAD

**Issue by enumag** [ergebnis/phpstan-rules#603]
#### Steps required to reproduce the problem

Define a trait with a protected method and a final class using this trait.

#### Expected Result

No error, methods defined in a trait should be ignored by this rule.

#### Actual Result

PrivateInFinalClassRule will report this method as that it should be private, however this is only true in the context of that class and may not be true for other usages of the trait.

**Comment by localheinz** [comment]
Do you still have this issue, @enumag?

I added a test case in #715, but it passes.

**Comment by enumag** [comment]
I no longer work on the project where I encountered it.

**Comment by localheinz** [comment]
Thank you, @enumag!
