### ISSUE TITLE
Intentions and Solutions

### ISSUE THREAD

**Issue by dmecke** [ergebnis/phpstan-rules#77]
First of all thank you for sharing your phpstan rules!

There are some rules (the nullable-rules to be precise) where I get the intention, but I am not sure how to avoid violations in some cases. I think there might also be a lack of understandment why some rules might be a good idea.

I think the rules would benefit from a brief description on _why_ they should be applied and _how_ to avoid violations.

**Comment by localheinz** [comment]
@dmecke 

Totally agree!

I‘ve meant to write a blog post a while ago, but never got around to actually do it. I’ll take care of it! 

👍

**Comment by localheinz** [comment]
@dmecke 

Still haven't gotten around to writing the post, but haven't forgotten - have recently moved, got lots of things to do. Hope to get it done soon!

**Comment by mablae** [comment]
Just giving this issue some "recent activity". (Not to build up any pressure but to express my interest in that blogpost.)

**Comment by jansor** [comment]
I totally @dmecke, for now i am not going to use this rules anymore, they causing confusion.
Example: why NoNullableReturnTypeDeclarationRule even exists? It is perfectlly fine that methods can return null. 
If we better understand why something is like this, then we can build better solutions.

Thanks for the effort on these rules. but for now i remove them from the programming.

**Comment by dmecke** [comment]
Well, for this specific rule the answer, I guess, is that nullable return types mean, that there are in fact two possible "types" that might be returned: the actual type or null. So every callee has to make sure to check for null, which makes the code much harder to read. If can rely on one specific type instead, you don't have to make any checks. You could achieve this with the null object pattern for example. And you might ask yourself: what does null actually mean? Maybe it's some kind of error case, so maybe an exception could be the better way to handle it.

Anyhow, these are just my thoughts and I am sure there is more reasoning about that topic.
