### ISSUE TITLE
Closures\StaticRule

### ISSUE THREAD

**Issue by Slamdunk** [ergebnis/phpstan-rules#90]
Related PHP-CS-Fixer rule: `static_lambda`

Lambdas should always be static to ensure no one can rebind them and so no one can alter their behavior.

**Comment by localheinz** [comment]
@Slamdunk 

A challenge I see here is when using lambdas for `phpspec/prophecy` - they can't be `static`.

**Comment by Slamdunk** [comment]
Issue somehow already discussed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3317

The fact that it can't be applied everywhere doesn't mean has little value: if you know the caveats on the tools you use, you can safely circumscribe its action range
